version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
      - myappdbvol:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: myapp
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp

  myapp:
    build: .

    depends_on:
      - db
    ports:
      - "820:80"

    environment:
      DATABASE_DRIVER: mysql
      DATABASE_DATABASE: myapp
      DATABASE_USERNAME: myapp
      DATABASE_PASSWORD: myapp
      DATABASE_SERVER: db
      DATABASE_PORT: 3306

volumes:
  myappdbvol: